const mutations = {
  SET_AUTH_STATUS: 'SET_AUTH_STATUS',
  LOGIN_LOADER: 'LOGIN_LOADER',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  SET_USER: 'SET_USER',
  PROFILE_LOADER: 'PROFILE_LOADER',
  SET_PUBLIC_CHATS: 'SET_PUBLIC_CHATS',
  SET_SELECTED_CHAT_ID: 'SET_SELECTED_CHAT_ID',
  CURRENT_CHAT: 'CURRENT_CHAT',
  CURRENT_CHAT_MESSAGESS: 'CURRENT_CHAT_MESSAGESS',
  SENDING_MSG: 'SENDING_MSG',
  ADD_NEW_MSG: 'ADD_NEW_MSG',
};

export default mutations;
